name: termflow
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section.
  fonts:
  - family: Poppins # Uygulama genelinde tema dosyasında çağıracağınız isim
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf # Regular (Normal) ağırlık
      - asset: assets/fonts/Poppins-Medium.ttf # Medium ağırlık
        weight: 500 # Flutter'a bu dosyanın Medium (500) olduğunu bildirir
      - asset: assets/fonts/Poppins-Bold.ttf # Bold ağırlık
        weight: 700 # Flutter'a bu dosyanın Bold (700) olduğunu bildirir
        # ... İhtiyacınız olan diğer Poppins varyasyonlarını buraya ekleyin